steal("can/test/test.js",
		"can/component/component_test.js",
		"can/construct/construct_test.js",
		"can/map/map_test.js", "can/list/list_test.js",
		"can/list/promise/promise_test.js",
		"can/observe/observe_test.js",
		"can/compute/compute_test.js",
		"can/model/model_test.js", "can/view/view_test.js",
		"can/view/stache/stache_test.js",
		"can/control/control_test.js",
		"can/route/route_test.js",
		"can/control/route/route_test.js",
		"can/route/pushstate/pushstate_test.js",
		"can/model/queue/queue_test.js",
		"can/construct/super/super_test.js",
		"can/construct/proxy/proxy_test.js",
		"can/map/lazy/lazy_test.js",
		"can/map/delegate/delegate_test.js",
		"can/map/setter/setter_test.js",
		"can/map/attributes/attributes_test.js",
		"can/map/validations/validations_test.js",
		"can/map/backup/backup_test.js",
		"can/map/list/list_test.js",
		"can/map/define/define_test.js",
		"can/list/sort/sort_test.js",
		"can/control/plugin/plugin_test.js",
		"can/view/modifiers/modifiers_test.js",
		"can/util/object/object_test.js",
		"can/util/fixture/fixture_test.js",
		"can/view/bindings/bindings_test.js",
		"can/view/live/live_test.js",
		"can/view/scope/scope_test.js",
		"can/util/string/string_test.js",
		"can/util/attr/attr_test.js", function() {});
