steal('can/dist/edge/can.jquery.js')
	.then('can/dist/edge/can.construct.proxy.js',
	  'can/dist/edge/can.construct.super.js',
	  'can/dist/edge/can.observe.attributes.js',
	  'can/dist/edge/can.observe.backup.js',
	  'can/dist/edge/can.observe.delegate.js',
	  'can/dist/edge/can.observe.setter.js',
	  'can/dist/edge/can.observe.validations.js',
	  'can/dist/edge/can.control.plugin.js')
.then('funcunit/qunit',
	  'can/util/fixture')
.then('can/construct/proxy/proxy_test.js',
	  'can/construct/super/super_test.js',
	  'can/observe/attributes/attributes_test.js',
	  'can/observe/delegate/delegate_test.js',
	  'can/observe/backup/backup_test.js',
	  'can/observe/setter/setter_test.js',
	  'can/observe/validations/validations_test.js',
	  'can/control/plugin/plugin_test.js')