require('../construct/construct_test');
require('../component/component_test');
require('../compute/compute_test');
require('../control/control_test');
require('../event/event_test');
require('../list/list_test');
require('../map/map_test');
// require('../route/route_test');
// require('../route/pushstate/pushstate_test');
require('../util/util_test');
// require('../view/autorender/autorender_test');
require('../view/import/import_test');
require('../view/live/live_test');
require('../view/node_lists/node_lists_test');
require('../view/parser/parser_test');
require('../view/scope/scope_test');
require('../view/stache/stache_test');
