steal.plugins('jquery/controller','jquery/controller/subscribe',
			  'jquery/view/ejs',
			  'jquery/model/store',
			  'jquery/model',
			  'jquery/dom/fixtures',
			  'jquery/dom/form_params')
     .resources()
     .models()
     .controllers()
     .views()