steal('can/util/jquery/jquery.1.7.1.js')
	.then('http://staging.donejs.com/can/dist/can.jquery-edge.js')
	.then('funcunit/qunit', 
		  'can/test/fixture.js')
	.then('can/test/mvc_test.js',
		  'can/construct/construct_test.js',
		  'can/observe/observe_test.js',
		  'can/view/view_test.js',
		  'can/control/control_test.js',
		  'can/model/model_test.js',
		  'can/view/ejs/ejs_test.js')
