(function(d,x,m){$.extend(d,jQuery,{trigger:function(a,b,c){a.trigger?a.trigger(b,c):$.event.trigger(b,c,a,true)},addEvent:function(a,b){$([this]).bind(a,b);return this},removeEvent:function(a,b){$([this]).unbind(a,b);return this},$:jQuery});$.each(["bind","unbind","undelegate","delegate"],function(a,b){d[b]=function(){var c=this[b]?this:$([this]);c[b].apply(c,arguments);return this}});$.each(["append","filter","addClass","remove","data","get"],function(a,b){d[b]=function(c){return c[b].apply(c,d.makeArray(arguments).slice(1))}});
var ya=/==/,za=/([A-Z]+)([A-Z][a-z])/g,Aa=/([a-z\d])([A-Z])/g,Ba=/([a-z\d])([A-Z])/g,X=/\{([^\}]+)\}/g,t=/"/g,Ca=/'/g,Y=function(a,b,c){return b in a?a[b]:c&&(a[b]={})},L=function(a){return/^f|o/.test(typeof a)},Z;d.String=d.extend({esc:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(t,"&#34;").replace(Ca,"&#39;")},getObject:Z=function(a,b,c){a=a?a.split("."):[];var e=a.length,f,g,h,i=0;b=d.isArray(b)?b:[b||x];if(e==0)return b[0];for(;f=b[i++];){for(h=
0;h<e-1&&L(f);h++)f=Y(f,a[h],c);if(L(f)){g=Y(f,a[h],c);if(g!==m){c===false&&delete f[a[h]];return g}}}},capitalize:function(a){return a.charAt(0).toUpperCase()+a.slice(1)},underscore:function(a){return a.replace(ya,"/").replace(za,"$1_$2").replace(Aa,"$1_$2").replace(Ba,"_").toLowerCase()},sub:function(a,b,c){var e=[];c=typeof c=="boolean"?!c:c;e.push(a.replace(X,function(f,g){f=Z(g,b,c);if(L(f)){e.push(f);return""}else return""+f}));return e.length<=1?e[0]:e},replacer:X,undHash:/_|-/});var M=0;d.Construct=
function(){if(arguments.length)return d.Construct.extend.apply(d.Construct,arguments)};d.extend(d.Construct,{newInstance:function(){var a=this.instance(),b;if(a.setup)b=a.setup.apply(a,arguments);if(a.init)a.init.apply(a,b||arguments);return a},_inherit:function(a,b){d.extend(b||a,a||{})},setup:function(a){this.defaults=d.extend(true,{},a.defaults,this.defaults)},instance:function(){M=1;var a=new this;M=0;return a},extend:function(a,b,c){function e(){if(!M)return this.constructor!==e&&arguments.length?
arguments.callee.extend.apply(arguments.callee,arguments):this.constructor.newInstance.apply(this.constructor,arguments)}if(typeof a!="string"){c=b;b=a;a=null}if(!c){c=b;b=null}c=c||{};var f=this,g,h,i,j;j=this.instance();this._inherit(c,j);for(g in this)if(this.hasOwnProperty(g))e[g]=this[g];this._inherit(b,e);if(a){i=a.split(".");h=i.pop();i=g=d.String.getObject(i.join("."),x,true);var k=d.String.underscore(a.replace(/\./g,"_")),l=d.String.underscore(h);g[h]=e}d.extend(e,{prototype:j,namespace:i,
shortName:h,_shortName:l,_fullName:k,constructor:e,fullName:a});e.prototype.constructor=e;f=[f].concat(d.makeArray(arguments));h=e.setup.apply(e,f);if(e.init)e.init.apply(e,h||f);return e}});var u=function(a){return typeof a==="object"&&a!==null&&a&&!(a instanceof Date)},N=function(a,b){return d.each(a,function(c,e){e&&e.unbind&&e.unbind("change"+b)})},O=function(a,b,c){if(a instanceof y)N([a],c._namespace);else a=d.isArray(a)?new y.List(a):new y(a);a.bind("change"+c._namespace,function(e){var f=
d.makeArray(arguments);e=f.shift();f[0]=b==="*"?c.indexOf(a)+"."+f[0]:b+"."+f[0];d.trigger(c,e,f)});return a},aa=0,z=null,ba=function(){if(!z){z=[];return true}},o=function(a,b,c){if(!a._init)if(z)z.push([a,{type:b,batchNum:ca},c]);else return d.trigger(a,b,c)},ca=1,da=function(){var a=z.slice(0);z=null;ca++;d.each(a,function(b,c){d.trigger.apply(d,c)})},H=function(a,b,c){a.each(function(e,f){c[e]=u(f)&&d.isFunction(f[b])?f[b]():f});return c},A=function(a){return function(){return d[a].apply(this,
arguments)}},I=A("addEvent");A=A("removeEvent");var P=function(a){return d.isArray(a)?a:(""+a).split(".")},y=d.Construct("can.Observe",{setup:function(){d.Construct.setup.apply(this,arguments)},bind:I,unbind:A},{setup:function(a){this._data={};this._namespace=".observe"+ ++aa;this._init=1;this.attr(a);delete this._init},attr:function(a,b){var c=typeof a;if(c!="string"&&c!="number")return this._attrs(a,b);else if(b===m){y.__reading&&y.__reading(this,a);return this._get(a)}else{this._set(a,b);return this}},
each:function(){return d.each.apply(null,[this.__get()].concat(d.makeArray(arguments)))},removeAttr:function(a){a=P(a);var b=a.shift(),c=this._data[b];if(a.length)return c.removeAttr(a);else{delete this._data[b];b in this.constructor.prototype||delete this[b];o(this,"change",[b,"remove",m,c]);o(this,b,m,c);return c}},_get:function(a){a=P(a);var b=this.__get(a.shift());return a.length?b?b._get(a):m:b},__get:function(a){return a?this._data[a]:this._data},_set:function(a,b){a=P(a);var c=a.shift(),e=
this.__get(c);if(u(e)&&a.length)e._set(a,b);else if(a.length)throw"can.Observe: Object does not exist";else this.__set(c,b,e)},__set:function(a,b,c){if(b!==c){var e=this.__get().hasOwnProperty(a)?"set":"add";this.___set(a,u(b)?O(b,a,this):b);o(this,"change",[a,e,b,c]);o(this,a,b,c);c&&N([c],this._namespace)}},___set:function(a,b){this._data[a]=b;a in this.constructor.prototype||(this[a]=b)},bind:I,unbind:A,serialize:function(){return H(this,"serialize",{})},_attrs:function(a,b){if(a===m)return H(this,
"attr",{});a=d.extend(true,{},a);var c,e=ba(),f=this;this.each(function(g,h){var i=a[g];if(i===m)b&&f.removeAttr(g);else{if(u(h)&&u(i))h.attr(i,b);else h!=i&&f._set(g,i);delete a[g]}});for(c in a){newVal=a[c];this._set(c,newVal)}e&&da();return this}}),Da=[].splice,Q=y("can.Observe.List",{setup:function(a,b){this.length=0;this._namespace=".list"+ ++aa;this._init=1;this.bind("change",d.proxy(this._changes,this));this.push.apply(this,d.makeArray(a||[]));d.extend(this,b);delete this._init},_changes:function(a,
b,c,e,f){if(!~b.indexOf("."))if(c==="add"){o(this,c,[e,+b]);o(this,"length",[this.length])}else if(c==="remove"){o(this,c,[f,+b]);o(this,"length",[this.length])}else o(this,c,[e,+b])},__get:function(a){return a?this[a]:this},___set:function(a,b){this[a]=b},serialize:function(){return H(this,"serialize",[])},splice:function(a,b){var c=d.makeArray(arguments),e;for(e=2;e<c.length;e++){var f=c[e];if(u(f))c[e]=O(f,"*",this)}if(b===m)b=c[1]=this.length-a;e=Da.apply(this,c);if(b>0){o(this,"change",[""+a,
"remove",m,e]);N(e,this._namespace)}c.length>2&&o(this,"change",[""+a,"add",c.slice(2),e]);return e},_attrs:function(a,b){if(a===m)return H(this,"attr",[]);a=a.slice(0);for(var c=Math.min(a.length,this.length),e=ba(),f=0;f<c;f++){var g=this[f],h=a[f];if(u(g)&&u(h))g.attr(h,b);else g!=h&&this._set(f,h)}if(a.length>this.length)this.push(a.slice(this.length));else a.length<this.length&&b&&this.splice(a.length);e&&da()}}),ea=function(a){return a[0]&&d.isArray(a[0])?a[0]:d.makeArray(a)};d.each({push:"length",
unshift:0},function(a,b){Q.prototype[a]=function(){for(var c=ea(arguments),e=b?this.length:0,f=0;f<c.length;f++){var g=c[f];if(u(g))c[f]=O(g,"*",this)}if(c.length==1&&this.comparator){this.splice(this.sortedIndex(c[0]),0,c[0]);return this.length}f=[][a].apply(this,c);if(this.comparator&&c.length>1){this.sort(null,true);o(this,"reset",[c])}else o(this,"change",[""+e,"add",c,m]);return f}});d.each({pop:"length",shift:0},function(a,b){Q.prototype[a]=function(){var c=ea(arguments),e=b&&this.length?this.length-
1:0;c=[][a].apply(this,c);o(this,"change",[""+e,"remove",m,[c]]);c&&c.unbind&&c.unbind("change"+this._namespace);return c}});Q.prototype.indexOf=[].indexOf||function(a){return d.inArray(a,this)};var Ea=/^\d+$/,Fa=/([^\[\]]+)|(\[\])/g,Ga=/([^?#]*)(#.*)?$/,fa=function(a){return decodeURIComponent(a.replace(/\+/g," "))};d.extend(d.String,{deparam:function(a){var b={};if(a&&Ga.test(a)){a=a.split("&");d.each(a,function(c,e){c=e.split("=");var f=fa(c.shift());e=fa(c.join("="));current=b;c=f.match(Fa);f=
0;for(var g=c.length-1;f<g;f++){current[c[f]]||(current[c[f]]=Ea.test(c[f+1])||c[f+1]=="[]"?[]:{});current=current[c[f]]}lastPart=c.pop();if(lastPart=="[]")current.push(e);else current[lastPart]=e})}return b}});var Ha=$.cleanData;$.cleanData=function(a){for(var b=0,c;(c=a[b])!==m;b++)$(c).triggerHandler("destroyed");Ha(a)};var ga=/\:([\w\.]+)/g,ha=/^(?:&[^=]+=[^&]*)+/,Ia=function(a){return d.map(a,function(b,c){return(c==="className"?"class":c)+'="'+d.String.esc(b)+'"'}).join(" ")},Ja=function(a,
b){for(var c=0,e=0;e<a.names.length;e++){if(!b.hasOwnProperty(a.names[e]))return-1;c++}return c},ia=true,B=x.location,w=d.each,p=d.extend;d.route=function(a,b){var c=[],e=a.replace(ga,function(f,g){c.push(g);return"([^\\/\\&]*)"});d.route.routes[a]={test:new RegExp("^"+e+"($|&)"),route:a,names:c,defaults:b||{},length:a.split("/").length};return d.route};p(d.route,{param:function(a){delete a.route;var b,c=0,e,f=a.route;delete a.route;f&&(b=d.route.routes[f])||w(d.route.routes,function(i,j){e=Ja(j,
a);if(e>c){b=j;c=e}});if(b){var g=p({},a);f=b.route.replace(ga,function(i,j){delete g[j];return a[j]===b.defaults[j]?"":encodeURIComponent(a[j])});var h;w(b.defaults,function(i,j){g[i]===j&&delete g[i]});h=d.param(g);return f+(h?"&"+h:"")}return d.isEmptyObject(a)?"":"&"+d.param(a)},deparam:function(a){var b={length:-1};w(d.route.routes,function(g,h){if(h.test.test(a)&&h.length>b.length)b=h});if(b.length>-1){var c=a.match(b.test),e=c.shift(),f=(e=a.substr(e.length-(c[c.length-1]==="&"?1:0)))&&ha.test(e)?
d.String.deparam(e.slice(1)):{};f=p(true,{},b.defaults,f);w(c,function(g,h){if(h&&h!=="&")f[b.names[g]]=decodeURIComponent(h)});f.route=b.route;return f}if(a.charAt(0)!=="&")a="&"+a;return ha.test(a)?d.String.deparam(a.slice(1)):{}},data:new d.Observe({}),routes:{},ready:function(a){if(a===false)ia=a;if(a===true||ia===true)ja();return d.route},url:function(a,b){if(b)a=p({},R,a);return"#!"+d.route.param(a)},link:function(a,b,c,e){return"<a "+Ia(p({href:d.route.url(b,e)},c))+">"+a+"</a>"},current:function(a){return B.hash==
"#!"+d.route.param(a)}});w(["bind","unbind","delegate","undelegate","attr","removeAttr"],function(a,b){d.route[b]=function(){return d.route.data[b].apply(d.route.data,arguments)}});var ka,R,ja=function(){var a=B.hash.substr(1,1)==="!"?B.hash.slice(2):B.hash.slice(1);R=d.route.deparam(a);d.route.attr(R,true)};d.bind.call(x,"hashchange",ja);d.route.bind("change",function(){clearTimeout(ka);ka=setTimeout(function(){B.hash="#!"+d.route.param(d.route.data.serialize())},1)});d.bind.call(document,"ready",
d.route.ready);I=function(a,b,c){d.bind.call(a,b,c);return function(){d.unbind.call(a,b,c)}};var C=d.isFunction;p=d.extend;w=d.each;var Ka=[].slice,La=$.event&&$.event.special||{},Ma=function(a,b,c,e){d.delegate.call(a,b,c,e);return function(){d.undelegate.call(a,b,c,e)}},la=function(a,b,c,e){return e?Ma(a,d.trim(e),b,c):I(a,b,c)},S=function(a,b){var c=typeof b=="string"?a[b]:b;return function(){a.called=b;return c.apply(a,[this.nodeName?d.$(this):this].concat(Ka.call(arguments,0)))}},Na=/[^\w]/,
ma=/\{([^\}]+)\}/g,Oa=/^(?:(.*?)\s)?([\w\.\:>]+)$/,T;d.Construct("can.Control",{setup:function(){d.Construct.setup.apply(this,arguments);if(this!==d.Control){var a=this.pluginName||this._fullName,b;a!=="can_control"&&this.plugin(a);this.actions={};for(b in this.prototype)if(!(b=="constructor"||!C(this.prototype[b])))if(this._isAction(b))this.actions[b]=this._action(b)}},_isAction:function(a){return Na.test(a)||La[a]||U[a]},plugin:function(){},_action:function(a,b){ma.lastIndex=0;if(!b&&ma.test(a))return null;
a=b?d.String.sub(a,[b,x]):a;b=d.isArray(a);var c=(b?a[1]:a).match(Oa);return{processor:U[c[2]]||T,parts:c,delegate:b?a[0]:m}},processors:{},defaults:{}},{setup:function(a,b){var c=this.constructor;a=d.get(d.$(a),0);var e=c.pluginName||c._fullName;this.element=d.$(a);e&&e!=="can_control"&&this.element.addClass(e);(a=d.data(this.element,"controls"))||d.data(this.element,"controls",a=[]);a.push(this);this.options=p(p({},c.defaults),b);this.on();return[this.element,this.options]},on:function(a,b,c,e){if(a===
m){this.off();a=this.constructor;b=this._bindings;c=a.actions;e=this.element;for(funcName in c)if(c.hasOwnProperty(funcName)){ready=c[funcName]||a._action(funcName,this.options);b.push(ready.processor(ready.delegate||e,ready.parts[2],ready.parts[1],funcName,this))}var f=S(this,"destroy");d.bind.call(e,"destroyed",f);b.push(function(g){d.unbind.call(g,"destroyed",f)});return b.length}if(typeof a=="string"){e=c;c=b;b=a;a=this.element}if(typeof e=="string")e=S(this,e);this._bindings.push(la(a,c,e,b));
return this._bindings.length},off:function(){var a=d.get(this.element,0);w(this._bindings||[],function(b,c){c(a)});this._bindings=[]},update:function(a){p(this.options,a);this.on()},destroy:function(){var a=this.constructor;a=a.pluginName||a._fullName;this.off();a&&a!=="can_control"&&this.element.removeClass(a);a=d.data(this.element,"controls");a.splice(d.inArray(this,a),1);d.trigger(this,"destroyed");this.element=null}});var U=d.Control.processors;T=function(a,b,c,e,f){return la(a,b,S(f,e),c)};w("change click contextmenu dblclick keydown keyup keypress mousedown mousemove mouseout mouseover mouseup reset resize scroll select submit focusin focusout mouseenter mouseleave".split(" "),
function(a,b){U[b]=T});var Pa=function(a){return a.replace(/^\/\//,"").replace(/[\/\.]/g,"_")};C=d.isFunction;var V=d.makeArray,Qa=1,q=d.view=function(a,b,c,e){a=d.render(a,b,c,e);if(d.isDeferred(a))return a.pipe(function(f){return d.view.frag(f)});return d.view.frag(a)};d.extend(d.view,{frag:function(a){a=d.buildFragment([a],[document.body]).fragment;a.childNodes.length||a.appendChild(document.createTextNode(""));return d.view.hookup(a)},hookup:function(a){var b=[],c,e,f,g=0;for(d.each(a.childNodes?
V(a.childNodes):a,function(h,i){if(i.nodeType!=3){b.push(i);b.push.apply(b,V(i.getElementsByTagName("*")))}});f=b[g++];)if(f.getAttribute&&(c=f.getAttribute("data-view-id"))&&(e=q.hookups[c])){e(f,c);delete q.hookups[c];f.removeAttribute("data-view-id")}return a},hookups:{},hook:function(a){var b=++Qa;q.hookups[b]=a;return b},cached:{},cache:true,register:function(a){this.types["."+a.suffix]=a},types:{},ext:".ejs",registerScript:function(){},preload:function(){}});d.render=function(a,b,c,e){if(C(c)){e=
c;c=m}var f=Ra(b);if(f.length){var g=new d.Deferred;f.push(na(a,true));d.when.apply(d,f).then(function(i){var j=V(arguments),k=j.pop();if(d.isDeferred(b))b=oa(i);else for(var l in b)if(d.isDeferred(b[l]))b[l]=oa(j.shift());j=k(b,c);g.resolve(j);e&&e(j)});return g}else{var h;f=typeof e==="function";g=na(a,f);if(f){h=g;g.then(function(i){e(i(b,c))})}else g.then(function(i){h=i(b,c)});return h}};d.isDeferred=function(a){return a&&C(a.then)&&C(a.pipe)};var pa=function(a,b){if(!a.match(/[^\s]/))throw"can.view ERROR: There is no template or an empty template at "+
b;},na=function(a,b){var c=a.match(/\.[\w\d]+$/),e,f,g,h=function(k){k=e.renderer(g,k);var l=new d.Deferred;l.resolve(k);if(q.cache)q.cached[g]=l;return l};if(f=document.getElementById(a))c="."+f.type.match(/\/(x\-)?(.+)/)[2];if(!c){c=q.ext;a+=q.ext}if(d.isArray(c))c=c[0];g=Pa(a);if(a.match(/^\/\//)){var i=a.substr(2);a=typeof steal==="undefined"?(a="/"+i):steal.root.mapJoin(i)}e=q.types[c];if(q.cached[g])return q.cached[g];else if(f)return h(f.innerHTML);else{var j=new d.Deferred;d.ajax({async:b,
url:a,dataType:"text",error:function(k){pa("",a);j.reject(k)},success:function(k){pa(k,a);j.resolve(e.renderer(g,k));if(q.cache)q.cached[g]=j}});return j}},Ra=function(a){var b=[];if(d.isDeferred(a))return[a];else for(var c in a)d.isDeferred(a[c])&&b.push(a[c]);return b},oa=function(a){return d.isArray(a)&&a.length===3&&a[1]==="success"?a[0]:a},qa=function(a,b,c){var e=new d.Deferred;a.then(function(){arguments[0]=b[c](arguments[0]);e.resolve.apply(e,arguments)},function(){e.resolveWith.apply(this,
arguments)});return e},Sa=0,D=function(a){return a[a.constructor.id]},E=function(a,b,c,e,f,g){if(typeof a=="string"){a=a.split(" ");a={url:a.pop(),type:a.pop()}}a.data=typeof b=="object"&&!d.isArray(b)?d.extend(a.data||{},b):b;a.url=d.String.sub(a.url,a.data,true);return d.ajax(d.extend({type:c||"post",dataType:e||"json",success:f,error:g},a))},ra=function(a,b,c,e,f){var g;g=[a.serialize()];var h=a.constructor,i;b=="destroy"&&g.shift();b!=="create"&&g.unshift(D(a));i=h[b].apply(h,g);g=i.pipe(function(j){a[f||
b+"d"](j,i);return a});if(i.abort)g.abort=function(){i.abort()};g.then(c,e);return g};ajaxMethods={create:function(a){return function(b){return E(a||this._shortName,b)}},update:function(a){return function(b,c){c=c||{};var e=this.id;if(c[e]&&c[e]!==b){c["new"+d.String.capitalize(b)]=c[e];delete c[e]}c[e]=b;return E(a||this._url,c,"put")}},destroy:function(a){return function(b){var c={};c[this.id]=b;return E(a||this._url,c,"delete")}},findAll:function(a){return function(b,c,e){return qa(E(a||this._shortName,
b,"get","json"),this,"models").then(c,e)}},findOne:function(a){return function(b,c,e){return qa(E(a||this._url,b,"get","json"),this,"model").then(c,e)}}};d.Observe("can.Model",{setup:function(){d.Observe.apply(this,arguments);if(this!==d.Model){var a=this;d.each(ajaxMethods,function(e,f){var g=a[e];if(typeof g!=="function")a[e]=f(g)});if(a.fullName=="can.Model")a.fullName="Model"+ ++Sa;if(x.jQuery){var b={},c="* "+a.fullName+".model";b[c+"s"]=d.proxy(a.models,a);b[c]=d.proxy(a.model,a);$.ajaxSetup({converters:b})}this.store=
{};this._url=this._shortName+"/{"+this.id+"}"}},id:"id",models:function(a){if(!a)return null;var b=this,c=new (this.List||sa),e=d.isArray(a),f=a instanceof sa;f=e?a:f?a.serialize():a.data;d.each(f,function(g,h){c.push(b.model(h))});e||d.each(a,function(g,h){if(g!=="data")c[g]=h});return c},model:function(a){if(!a)return null;if(a instanceof this)a=a.serialize();return this.store[a.id]||new this(a)}},{isNew:function(){var a=D(this);return!(a||a===0)},save:function(a,b){return ra(this,this.isNew()?
"create":"update",a,b)},destroy:function(a,b){return ra(this,"destroy",a,b,"destroyed")},bind:function(){if(!this._bindings){this.constructor.store[D(this)]=this;this._bindings=0}this._bindings++;return d.Observe.prototype.bind.apply(this,arguments)},unbind:function(){this._bindings--;this._bindings||delete this.constructor.store[D(this)];return d.Observe.prototype.unbind.apply(this,arguments)},___set:function(a,b){d.Observe.prototype.___set.call(this,a,b);if(a===this.constructor.id&&this._bindings)this.constructor.store[D(this)]=
this}});d.each(["created","updated","destroyed"],function(a,b){d.Model.prototype[b]=function(c){var e=this.constructor;c&&typeof c=="object"&&this.attr(c.attr?c.attr():c);d.trigger(this,b);d.trigger(this,"change",b);d.trigger(e,b,this)}});var sa=d.Observe.List("can.Model.List",{setup:function(){d.Observe.List.prototype.setup.apply(this,arguments);var a=this;this.bind("change",function(b,c){/\w+\.destroyed/.test(c)&&a.splice(a.indexOf(b.target),1)})}});d.Control.processors.route=function(a,b,c,e,f){d.route(c||
"");var g,h=function(i){if(d.route.attr("route")===(c||"")&&(i.batchNum===m||i.batchNum!==g)){g=i.batchNum;i=d.route.attr();delete i.route;f[e](i)}};d.route.bind("change",h);return function(){d.route.unbind("change",h)}};var Ta=function(a){eval(a)};p=d.extend;var Ua=/\r\n/g,Va=/\r/g,Wa=/\n/g,Xa=/\\/g,Ya=/\t/g,Za=/\{/g,$a=/\}/g,ta=/\s*\(([\$\w]+)\)\s*->([^\n]*)/,ab=/([^\s]+)=$/,bb=/__!!__/g,cb={"":"span",table:"tr",tr:"td",ol:"li",ul:"li",tbody:"tr",thead:"tr",tfoot:"tr"},db=function(a){return a.replace(Xa,
"\\\\").replace(Wa,"\\n").replace(/"/g,'\\"').replace(Ya,"\\t")},ua=function(a){var b=a.match(Za);a=a.match($a);return(b?b.length:0)-(a?a.length:0)},J=function(a,b,c){d.each(a,function(e,f){f.obj.bind(f.attr,c)});d.bind.call(b,"destroyed",function(){d.each(a,function(e,f){f.obj.unbind(f.attr,f.cb)})})},wa=function(a){return typeof a=="string"||typeof a=="number"?d.String.esc(""+a):va(a)},va=function(a){if(typeof a=="string")return a;if(a===null||a===m)return"";var b=a.hookup&&function(c,e){a.hookup.call(a,
c,e)}||typeof a=="function"&&a;if(b)return"data-view-id='"+d.view.hook(b)+"'";return""+a},r=function(a){if(this.constructor!=r){var b=new r(a);return function(c,e){return b.render(c,e)}}if(typeof a=="function")this.template={fn:a};else{p(this,a);this.template=eb(this.text,this.name)}};d.EJS=r;r.prototype.render=function(a,b){a=a||{};return this.template.fn.call(a,a,new r.Helpers(a,b||{}))};p(r,{txt:function(a,b,c,e,f){if(d.Observe)d.Observe.__reading=function(j,k){g.push({obj:j,attr:k})};var g=[],
h=e.call(c);d.Observe&&delete d.Observe.__reading;if(!g.length)return(f||b!==0?wa:va)(h);a=cb[a]||"span";if(b==0)return"<"+a+" data-view-id='"+d.view.hook(f?function(j){var k=j.parentNode,l=document.createTextNode(h);k.insertBefore(l,j);k.removeChild(j);J(g,k,function(){l.nodeValue=e.call(c)})}:function(j){var k=function(n,s){n=d.view.frag(n);var v=d.$(d.map(n.childNodes,function(fb){return fb})),K=s[s.length-1];K.nextSibling?K.parentNode.insertBefore(n,K.nextSibling):K.parentNode.appendChild(n);
d.remove(d.$(s));return v},l=k(h,[j]);J(g,j.parentNode,function(){l=k(e.call(c),l)})})+"'></"+a+">";else if(b===1){var i=e.call(c).replace(/['"]/g,"").split("=")[0];F.push(function(j){J(g,j,function(){var k=(e.call(c)||"").replace(/['"]/g,"").split("=");newAttrName=k[0];newAttrName!=i&&i&&j.removeAttribute(i);newAttrName&&j.setAttribute(newAttrName,k[1])})});return h}else{F.push(function(j){var k=d.$(j),l;(l=d.data(k,"hooks"))||d.data(k,"hooks",l={});var n=j.getAttribute(b);k=n.split("__!!__");var s;
if(l[b])l[b].funcs.push(e);else l[b]={render:function(){var v=0;return n.replace(bb,function(){return wa(s.funcs[v++].call(c))})},funcs:[e],batchNum:m};s=l[b];k.splice(1,0,h);j.setAttribute(b,k.join(""));J(g,j,function(v){if(v.batchNum===m||v.batchNum!==s.batchNum){s.batchNum=v.batchNum;j.setAttribute(b,s.render())}})});return"__!!__"}},esc:function(a,b,c,e){return r.txt(a,b,c,e,true)},pending:function(){if(F.length){var a=F.slice(0);F=[];return" data-view-id='"+d.view.hook(function(b){d.each(a,function(c,
e){e(b)})})+"'"}else return""}});var gb=/(<%%|%%>|<%==|<%=|<%#|<%|%>|<|>|"|')/,G=null,W=t=null,xa=function(){return t?"'"+W.match(ab)[1]+"'":G?1:0},F=[],eb=function(a,b){a=a.replace(Ua,"\n").replace(Va,"\n").split(gb);var c="",e=["var ___v1ew = [];"],f=function(s,v){e.push("___v1ew.push(",'"',db(s),'"'+(v||"")+");")},g=[],h,i=null,j=false,k="",l=0,n;for(G=t=W=null;(n=a[l++])!==m;){if(i===null)switch(n){case "<%":case "<%=":case "<%==":j=1;case "<%#":i=n;c.length>0&&f(c);c="";break;case "<%%":c+="<%";
break;case "<":G=1;c+=n;j=0;break;case ">":G=0;if(j){f(c,',can.EJS.pending(),">"');c=""}else c+=n;break;case "'":case '"':if(G)if(t&&t===n)t=null;else if(t===null){t=n;W=h}default:if(h==="<")k=n.split(" ")[0];c+=n;break}else switch(n){case "%>":switch(i){case "<%":h=ua(c);if(h==1){e.push("___v1ew.push(","can.EJS.txt('"+k+"',"+xa()+",this,function(){","var ___v1ew = [];",c);g.push({before:"",after:"return ___v1ew.join('')}));"})}else{i=g.length&&h==-1?g.pop():{after:";"};i.before&&e.push(i.before);
e.push(c,";",i.after)}break;case "<%=":case "<%==":(h=ua(c))&&g.push({before:"return ___v1ew.join('')",after:"}));"});if(ta.test(c)){c=c.match(ta);c="function(__){var "+c[1]+"=can.$(__);"+c[2]+"}"}e.push("___v1ew.push(","can.EJS."+(i==="<%="?"esc":"txt")+"('"+k+"',"+xa()+",this,function(){ return ",c,h?"var ___v1ew = [];":"}));");break}i=null;c="";break;case "<%%":c+="<%";break;default:c+=n;break}h=n}c.length>0&&f(c);e.push(";");a={out:"with(_VIEW) { with (_CONTEXT) {"+e.join("")+" return ___v1ew.join('')}}"};
Ta.call(a,"this.fn = (function(_CONTEXT,_VIEW){"+a.out+"});\r\n//@ sourceURL="+b+".js");return a};r.Helpers=function(a,b){this._data=a;this._extras=b;p(this,b)};r.Helpers.prototype={view:function(a,b,c){return $View(a,b||this._data,c||this._extras)},list:function(a,b){a.attr("length");for(var c=0,e=a.length;c<e;c++)b(a[c],c,a)}};d.view.register({suffix:"ejs",script:function(a,b){return"can.EJS(function(_CONTEXT,_VIEW) { "+(new r({text:b,name:a})).template.out+" })"},renderer:function(a,b){return r({text:b,
name:a})}})})(can={},window);
