(function(d,y,n){$.extend(d,jQuery,{trigger:function(a,b,c){a.trigger?a.trigger(b,c):$.event.trigger(b,c,a,true)},addEvent:function(a,b){$([this]).bind(a,b);return this},removeEvent:function(a,b){$([this]).unbind(a,b);return this},$:jQuery});$.each(["bind","unbind","undelegate","delegate"],function(a,b){d[b]=function(){var c=this[b]?this:$([this]);c[b].apply(c,arguments);return this}});$.each(["append","filter","addClass","remove","data","get"],function(a,b){d[b]=function(c){return c[b].apply(c,d.makeArray(arguments).slice(1))}});
var t={undHash:/_|-/,colons:/::/,words:/([A-Z]+)([A-Z][a-z])/g,lowUp:/([a-z\d])([A-Z])/g,dash:/([a-z\d])([A-Z])/g,replacer:/\{([^\}]+)\}/g,dot:/\./,quote:/"/g,singleQuote:/'/g},Y=function(a,b,c){return a[b]!==n?a[b]:c&&(a[b]={})},M=function(a){return/^f|o/.test(typeof a)},Z;d.String=d.extend({esc:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(t.quote,"&#34;").replace(t.singleQuote,"&#39;")},getObject:Z=function(a,b,c){a=a?a.split(t.dot):[];var e=a.length,
f,g,h,i=0;b=d.isArray(b)?b:[b||y];if(e==0)return b[0];for(;f=b[i++];){for(h=0;h<e-1&&M(f);h++)f=Y(f,a[h],c);if(M(f)){g=Y(f,a[h],c);if(g!==n){c===false&&delete f[a[h]];return g}}}},capitalize:function(a){return a.charAt(0).toUpperCase()+a.substr(1)},underscore:function(a){return a.replace(t.colons,"/").replace(t.words,"$1_$2").replace(t.lowUp,"$1_$2").replace(t.dash,"_").toLowerCase()},sub:function(a,b,c){var e=[];c=typeof c=="boolean"?!c:c;e.push(a.replace(t.replacer,function(f,g){f=Z(g,b,c);if(M(f)){e.push(f);
return""}else return""+f}));return e.length<=1?e[0]:e},_regs:t});var N=false;d.Construct=function(){if(arguments.length)return d.Construct.extend.apply(d.Construct,arguments)};d.extend(d.Construct,{newInstance:function(){var a=this.instance(),b;if(a.setup)b=a.setup.apply(a,arguments);if(a.init)a.init.apply(a,d.isArray(b)?b:arguments);return a},_inherit:function(a,b,c){d.extend(c||a,a||{})},setup:function(a){this.defaults=d.extend(true,{},a.defaults,this.defaults)},instance:function(){N=true;var a=
new this;N=false;return a},extend:function(a,b,c){function e(){if(!N)return this.constructor!==e&&arguments.length?arguments.callee.extend.apply(arguments.callee,arguments):this.constructor.newInstance.apply(this.constructor,arguments)}if(typeof a!="string"){c=b;b=a;a=null}if(!c){c=b;b=null}c=c||{};var f=this,g=this.prototype,h,i,j,k;k=this.instance();this._inherit(c,g,k);for(h in this)if(this.hasOwnProperty(h))e[h]=this[h];this._inherit(b,this,e);if(a){j=a.split(/\./);i=j.pop();j=g=d.String.getObject(j.join("."),
y,true);var l=d.String.underscore(a.replace(/\./g,"_")),m=d.String.underscore(i);g[i]=e}d.extend(e,{prototype:k,namespace:j,shortName:i,_shortName:m,_fullName:l,constructor:e,fullName:a});e.prototype.constructor=e;f=[f].concat(d.makeArray(arguments));i=e.setup.apply(e,f);if(e.init)e.init.apply(e,i||f);return e}});var u=function(a){return typeof a==="object"&&a!==null&&a&&!(a instanceof Date)},O=function(a,b){return d.each(a,function(c,e){e&&e.unbind&&e.unbind("change"+b)})},P=function(a,b,c){if(a instanceof
z)O([a],c._namespace);else a=d.isArray(a)?new z.List(a):new z(a);a.bind("change"+c._namespace,function(e){var f=d.makeArray(arguments);e=f.shift();f[0]=b==="*"?c.indexOf(a)+"."+f[0]:b+"."+f[0];d.trigger(c,e,f)});return a},aa=0,A=null,ba=function(){if(!A){A=[];return true}},o=function(a,b,c){if(!a._init)if(A)A.push([a,{type:b,batchNum:ca},c]);else return d.trigger(a,b,c)},ca=1,da=function(){var a=A.slice(0);A=null;ca++;d.each(a,function(b,c){d.trigger.apply(d,c)})},I=function(a,b,c){a.each(function(e,
f){c[e]=u(f)&&d.isFunction(f[b])?f[b]():f});return c},B=function(a){return function(){return d[a].apply(this,arguments)}},J=B("addEvent");B=B("removeEvent");var Q=function(a){return d.isArray(a)?a:(""+a).split(".")},z=d.Construct("can.Observe",{setup:function(){d.Construct.setup.apply(this,arguments)},bind:J,unbind:B},{setup:function(a){this._data={};this._namespace=".observe"+ ++aa;this._init=1;this.attr(a);delete this._init},attr:function(a,b){var c=typeof a;if(c!="string"&&c!="number")return this._attrs(a,
b);else if(b===n){z.__reading&&z.__reading(this,a);return this._get(a)}else{this._set(a,b);return this}},each:function(){return d.each.apply(null,[this.__get()].concat(d.makeArray(arguments)))},removeAttr:function(a){a=Q(a);var b=a.shift(),c=this._data[b];if(a.length)return c.removeAttr(a);else{delete this._data[b];b in this.constructor.prototype||delete this[b];o(this,"change",[b,"remove",n,c]);o(this,b,n,c);return c}},_get:function(a){a=Q(a);var b=this.__get(a.shift());return a.length?b?b._get(a):
n:b},__get:function(a){return a?this._data[a]:this._data},_set:function(a,b){a=Q(a);var c=a.shift(),e=this.__get(c);if(u(e)&&a.length)e._set(a,b);else if(a.length)throw"can.Observe: set a property on an object that does not exist";else this.__set(c,b,e)},__set:function(a,b,c){if(b!==c){var e=this.__get().hasOwnProperty(a)?"set":"add";this.___set(a,u(b)?P(b,a,this):b);o(this,"change",[a,e,b,c]);o(this,a,b,c);c&&O([c],this._namespace)}},___set:function(a,b){this._data[a]=b;a in this.constructor.prototype||
(this[a]=b)},bind:J,unbind:B,serialize:function(){return I(this,"serialize",{})},_attrs:function(a,b){if(a===n)return I(this,"attr",{});a=d.extend(true,{},a);var c,e=ba(),f=this;this.each(function(g,h){var i=a[g];if(i===n)b&&f.removeAttr(g);else{if(u(h)&&u(i))h.attr(i,b);else h!=i&&f._set(g,i);delete a[g]}});for(c in a){newVal=a[c];this._set(c,newVal)}e&&da();return this}}),ya=[].splice,R=z("can.Observe.List",{setup:function(a,b){this.length=0;this._namespace=".list"+ ++aa;this._init=1;this.bind("change",
d.proxy(this._changes,this));this.push.apply(this,d.makeArray(a||[]));d.extend(this,b);delete this._init},_changes:function(a,b,c,e,f){if(!~b.indexOf("."))if(c==="add"){o(this,c,[e,+b]);o(this,"length",[this.length])}else if(c==="remove"){o(this,c,[f,+b]);o(this,"length",[this.length])}else o(this,c,[e,+b])},__get:function(a){return a?this[a]:this},___set:function(a,b){this[a]=b},serialize:function(){return I(this,"serialize",[])},splice:function(a,b){var c=d.makeArray(arguments),e;for(e=2;e<c.length;e++){var f=
c[e];if(u(f))c[e]=P(f,"*",this)}if(b===n)b=c[1]=this.length-a;e=ya.apply(this,c);if(b>0){o(this,"change",[""+a,"remove",n,e]);O(e,this._namespace)}c.length>2&&o(this,"change",[""+a,"add",c.slice(2),e]);return e},_attrs:function(a,b){if(a===n)return I(this,"attr",[]);a=a.slice(0);for(var c=Math.min(a.length,this.length),e=ba(),f=0;f<c;f++){var g=this[f],h=a[f];if(u(g)&&u(h))g.attr(h,b);else g!=h&&this._set(f,h)}if(a.length>this.length)this.push(a.slice(this.length));else a.length<this.length&&b&&this.splice(a.length);
e&&da()}}),ea=function(a){return a[0]&&d.isArray(a[0])?a[0]:d.makeArray(a)};d.each({push:"length",unshift:0},function(a,b){R.prototype[a]=function(){for(var c=ea(arguments),e=b?this.length:0,f=0;f<c.length;f++){var g=c[f];if(u(g))c[f]=P(g,"*",this)}if(c.length==1&&this.comparator){this.splice(this.sortedIndex(c[0]),0,c[0]);return this.length}f=[][a].apply(this,c);if(this.comparator&&c.length>1){this.sort(null,true);o(this,"reset",[c])}else o(this,"change",[""+e,"add",c,n]);return f}});d.each({pop:"length",
shift:0},function(a,b){R.prototype[a]=function(){var c=ea(arguments),e=b&&this.length?this.length-1:0;c=[][a].apply(this,c);o(this,"change",[""+e,"remove",n,[c]]);c&&c.unbind&&c.unbind("change"+this._namespace);return c}});R.prototype.indexOf=[].indexOf||function(a){return d.inArray(a,this)};var za=/^\d+$/,Aa=/([^\[\]]+)|(\[\])/g,Ba=/([^?#]*)(#.*)?$/,fa=function(a){return decodeURIComponent(a.replace(/\+/g," "))};d.extend(d.String,{deparam:function(a){var b={};if(a&&Ba.test(a)){a=a.split("&");d.each(a,
function(c,e){c=e.split("=");var f=fa(c.shift());e=fa(c.join("="));current=b;c=f.match(Aa);f=0;for(var g=c.length-1;f<g;f++){current[c[f]]||(current[c[f]]=za.test(c[f+1])||c[f+1]=="[]"?[]:{});current=current[c[f]]}lastPart=c.pop();if(lastPart=="[]")current.push(e);else current[lastPart]=e})}return b}});var Ca=$.cleanData;$.cleanData=function(a){for(var b=0,c;(c=a[b])!==n;b++)$(c).triggerHandler("destroyed");Ca(a)};var ga=/\:([\w\.]+)/g,ha=/^(?:&[^=]+=[^&]*)+/,Da=function(a){return d.map(a,function(b,
c){return(c==="className"?"class":c)+'="'+d.String.esc(b)+'"'}).join(" ")},Ea=function(a,b){for(var c=0,e=0;e<a.names.length;e++){if(!b.hasOwnProperty(a.names[e]))return-1;c++}return c},ia=true,C=y.location,w=d.each,p=d.extend;d.route=function(a,b){var c=[],e=a.replace(ga,function(f,g){c.push(g);return"([^\\/\\&]*)"});d.route.routes[a]={test:new RegExp("^"+e+"($|&)"),route:a,names:c,defaults:b||{},length:a.split("/").length};return d.route};p(d.route,{param:function(a){delete a.route;var b,c=0,e,
f=a.route;delete a.route;f&&(b=d.route.routes[f])||w(d.route.routes,function(i,j){e=Ea(j,a);if(e>c){b=j;c=e}});if(b){var g=p({},a);f=b.route.replace(ga,function(i,j){delete g[j];return a[j]===b.defaults[j]?"":encodeURIComponent(a[j])});var h;w(b.defaults,function(i,j){g[i]===j&&delete g[i]});h=d.param(g);return f+(h?"&"+h:"")}return d.isEmptyObject(a)?"":"&"+d.param(a)},deparam:function(a){var b={length:-1};w(d.route.routes,function(g,h){if(h.test.test(a)&&h.length>b.length)b=h});if(b.length>-1){var c=
a.match(b.test),e=c.shift(),f=(e=a.substr(e.length-(c[c.length-1]==="&"?1:0)))&&ha.test(e)?d.String.deparam(e.slice(1)):{};f=p(true,{},b.defaults,f);w(c,function(g,h){if(h&&h!=="&")f[b.names[g]]=decodeURIComponent(h)});f.route=b.route;return f}if(a.charAt(0)!=="&")a="&"+a;return ha.test(a)?d.String.deparam(a.slice(1)):{}},data:new d.Observe({}),routes:{},ready:function(a){if(a===false)ia=a;if(a===true||ia===true)ja();return d.route},url:function(a,b){if(b)a=p({},S,a);return"#!"+d.route.param(a)},
link:function(a,b,c,e){return"<a "+Da(p({href:d.route.url(b,e)},c))+">"+a+"</a>"},current:function(a){return C.hash=="#!"+d.route.param(a)}});w(["bind","unbind","delegate","undelegate","attr","removeAttr"],function(a,b){d.route[b]=function(){return d.route.data[b].apply(d.route.data,arguments)}});var ka,S,ja=function(){var a=C.hash.substr(1,1)==="!"?C.hash.slice(2):C.hash.slice(1);S=d.route.deparam(a);d.route.attr(S,true)};d.bind.call(y,"hashchange",ja);d.route.bind("change",function(){clearTimeout(ka);
ka=setTimeout(function(){C.hash="#!"+d.route.param(d.route.data.serialize())},1)});d.bind.call(document,"ready",d.route.ready);J=function(a,b,c){d.bind.call(a,b,c);return function(){d.unbind.call(a,b,c)}};var D=d.isFunction;p=d.extend;w=d.each;var Fa=[].slice,Ga=$.event&&$.event.special||{},Ha=function(a,b,c,e){d.delegate.call(a,b,c,e);return function(){d.undelegate.call(a,b,c,e)}},la=function(a,b,c,e){return e?Ha(a,d.trim(e),b,c):J(a,b,c)},T=function(a,b){var c=typeof b=="string"?a[b]:b;return function(){a.called=
b;return c.apply(a,[this.nodeName?d.$(this):this].concat(Fa.call(arguments,0)))}},Ia=/[^\w]/,ma=/\{([^\}]+)\}/g,Ja=/^(?:(.*?)\s)?([\w\.\:>]+)$/,U;d.Construct("can.Control",{setup:function(){d.Construct.setup.apply(this,arguments);if(this!==d.Control){var a=this.pluginName||this._fullName,b;a!=="can_control"&&this.plugin(a);this.actions={};for(b in this.prototype)if(!(b=="constructor"||!D(this.prototype[b])))if(this._isAction(b))this.actions[b]=this._action(b)}},_isAction:function(a){return Ia.test(a)||
Ga[a]||V[a]},plugin:function(){},_action:function(a,b){ma.lastIndex=0;if(!b&&ma.test(a))return null;a=b?d.String.sub(a,[b,y]):a;b=d.isArray(a);var c=(b?a[1]:a).match(Ja);return{processor:V[c[2]]||U,parts:c,delegate:b?a[0]:n}},processors:{},defaults:{}},{setup:function(a,b){var c=this.constructor;a=d.get(d.$(a),0);var e=c.pluginName||c._fullName;this.element=d.$(a);e&&e!=="can_control"&&this.element.addClass(e);(a=d.data(this.element,"controls"))||d.data(this.element,"controls",a=[]);a.push(this);
this.options=p(p({},c.defaults),b);this.on();return[this.element,this.options]},on:function(a,b,c,e){if(a===n){this.off();a=this.constructor;b=this._bindings;c=a.actions;e=this.element;for(funcName in c)if(c.hasOwnProperty(funcName)){ready=c[funcName]||a._action(funcName,this.options);b.push(ready.processor(ready.delegate||e,ready.parts[2],ready.parts[1],funcName,this))}var f=T(this,"destroy");d.bind.call(e,"destroyed",f);b.push(function(g){d.unbind.call(g,"destroyed",f)});return b.length}if(typeof a==
"string"){e=c;c=b;b=a;a=this.element}if(typeof e=="string")e=T(this,e);this._bindings.push(la(a,c,e,b));return this._bindings.length},off:function(){var a=d.get(this.element,0);w(this._bindings||[],function(b,c){c(a)});this._bindings=[]},update:function(a){p(this.options,a);this.on()},destroy:function(){var a=this.constructor;a=a.pluginName||a._fullName;this.off();a&&a!=="can_control"&&this.element.removeClass(a);a=d.data(this.element,"controls");a.splice(d.inArray(this,a),1);d.trigger(this,"destroyed");
this.element=null}});var V=d.Control.processors;U=function(a,b,c,e,f){return la(a,b,T(f,e),c)};w("change click contextmenu dblclick keydown keyup keypress mousedown mousemove mouseout mouseover mouseup reset resize scroll select submit focusin focusout mouseenter mouseleave".split(" "),function(a,b){V[b]=U});var Ka=function(a){return a.replace(/^\/\//,"").replace(/[\/\.]/g,"_")};D=d.isFunction;var W=d.makeArray,La=1,q=d.view=function(a,b,c,e){a=d.render(a,b,c,e);if(d.isDeferred(a))return a.pipe(function(f){return d.view.frag(f)});
return d.view.frag(a)};d.extend(d.view,{frag:function(a){a=d.buildFragment([a],[document.body]).fragment;a.childNodes.length||a.appendChild(document.createTextNode(""));return d.view.hookup(a)},hookup:function(a){var b=[],c,e,f,g=0;for(d.each(a.childNodes?W(a.childNodes):a,function(h,i){if(i.nodeType!=3){b.push(i);b.push.apply(b,W(i.getElementsByTagName("*")))}});f=b[g++];)if(f.getAttribute&&(c=f.getAttribute("data-view-id"))&&(e=q.hookups[c])){e(f,c);delete q.hookups[c];f.removeAttribute("data-view-id")}return a},
hookups:{},hook:function(a){var b=++La;q.hookups[b]=a;return b},cached:{},cache:true,register:function(a){this.types["."+a.suffix]=a},types:{},ext:".ejs",registerScript:function(){},preload:function(){}});d.render=function(a,b,c,e){if(D(c)){e=c;c=n}var f=Ma(b);if(f.length){var g=new d.Deferred;f.push(na(a,true));d.when.apply(d,f).then(function(i){var j=W(arguments),k=j.pop();if(d.isDeferred(b))b=oa(i);else for(var l in b)if(d.isDeferred(b[l]))b[l]=oa(j.shift());j=k(b,c);g.resolve(j);e&&e(j)});return g}else{var h;
f=typeof e==="function";g=na(a,f);if(f){h=g;g.then(function(i){e(i(b,c))})}else g.then(function(i){h=i(b,c)});return h}};d.isDeferred=function(a){return a&&D(a.then)&&D(a.pipe)};var pa=function(a,b){if(!a.match(/[^\s]/))throw"can.view ERROR: There is no template or an empty template at "+b;},na=function(a,b){var c=a.match(/\.[\w\d]+$/),e,f,g,h=function(k){k=e.renderer(g,k);var l=new d.Deferred;l.resolve(k);if(q.cache)q.cached[g]=l;return l};if(f=document.getElementById(a))c="."+f.type.match(/\/(x\-)?(.+)/)[2];
if(!c){c=q.ext;a+=q.ext}if(d.isArray(c))c=c[0];g=Ka(a);if(a.match(/^\/\//)){var i=a.substr(2);a=typeof steal==="undefined"?(a="/"+i):steal.root.mapJoin(i)}e=q.types[c];if(q.cached[g])return q.cached[g];else if(f)return h(f.innerHTML);else{var j=new d.Deferred;d.ajax({async:b,url:a,dataType:"text",error:function(k){pa("",a);j.reject(k)},success:function(k){pa(k,a);j.resolve(e.renderer(g,k));if(q.cache)q.cached[g]=j}});return j}},Ma=function(a){var b=[];if(d.isDeferred(a))return[a];else for(var c in a)d.isDeferred(a[c])&&
b.push(a[c]);return b},oa=function(a){return d.isArray(a)&&a.length===3&&a[1]==="success"?a[0]:a},qa=function(a,b,c){var e=new d.Deferred;a.then(function(){arguments[0]=b[c](arguments[0]);e.resolve.apply(e,arguments)},function(){e.resolveWith.apply(this,arguments)});return e},Na=0,E=function(a){return a[a.constructor.id]},F=function(a,b,c,e,f,g){if(typeof a=="string"){a=a.split(" ");a={url:a.pop(),type:a.pop()}}a.data=typeof b=="object"&&!d.isArray(b)?d.extend(a.data||{},b):b;a.url=d.String.sub(a.url,
a.data,true);return d.ajax(d.extend({type:c||"post",dataType:e||"json",success:f,error:g},a))},ra=function(a,b,c,e,f){var g;g=[a.serialize()];var h=a.constructor,i;b=="destroy"&&g.shift();b!=="create"&&g.unshift(E(a));i=h[b].apply(h,g);g=i.pipe(function(j){a[f||b+"d"](j,i);return a});if(i.abort)g.abort=function(){i.abort()};g.then(c,e);return g};ajaxMethods={create:function(a){return function(b){return F(a||this._shortName,b)}},update:function(a){return function(b,c){c=c||{};var e=this.id;if(c[e]&&
c[e]!==b){c["new"+d.String.capitalize(b)]=c[e];delete c[e]}c[e]=b;return F(a||this._url,c,"put")}},destroy:function(a){return function(b){var c={};c[this.id]=b;return F(a||this._url,c,"delete")}},findAll:function(a){return function(b,c,e){return qa(F(a||this._shortName,b,"get","json"),this,"models").then(c,e)}},findOne:function(a){return function(b,c,e){return qa(F(a||this._url,b,"get","json"),this,"model").then(c,e)}}};d.Observe("can.Model",{setup:function(){d.Observe.apply(this,arguments);if(this!==
d.Model){var a=this;d.each(ajaxMethods,function(e,f){var g=a[e];if(typeof g!=="function")a[e]=f(g)});if(a.fullName=="can.Model")a.fullName="Model"+ ++Na;if(y.jQuery){var b={},c="* "+a.fullName+".model";b[c+"s"]=d.proxy(a.models,a);b[c]=d.proxy(a.model,a);$.ajaxSetup({converters:b})}this.store={};this._url=this._shortName+"/{"+this.id+"}"}},id:"id",models:function(a){if(!a)return null;var b=this,c=new (this.List||sa),e=d.isArray(a),f=a instanceof sa;f=e?a:f?a.serialize():a.data;d.each(f,function(g,
h){c.push(b.model(h))});e||d.each(a,function(g,h){if(g!=="data")c[g]=h});return c},model:function(a){if(!a)return null;if(a instanceof this)a=a.serialize();return this.store[a.id]||new this(a)}},{isNew:function(){var a=E(this);return!(a||a===0)},save:function(a,b){return ra(this,this.isNew()?"create":"update",a,b)},destroy:function(a,b){return ra(this,"destroy",a,b,"destroyed")},bind:function(){if(!this._bindings){this.constructor.store[E(this)]=this;this._bindings=0}this._bindings++;return d.Observe.prototype.bind.apply(this,
arguments)},unbind:function(){this._bindings--;this._bindings||delete this.constructor.store[E(this)];return d.Observe.prototype.unbind.apply(this,arguments)},___set:function(a,b){d.Observe.prototype.___set.call(this,a,b);if(a===this.constructor.id&&this._bindings)this.constructor.store[E(this)]=this}});d.each(["created","updated","destroyed"],function(a,b){d.Model.prototype[b]=function(c){var e=this.constructor;c&&typeof c=="object"&&this.attr(c.attr?c.attr():c);d.trigger(this,b);d.trigger(this,
"change",b);d.trigger(e,b,this)}});var sa=d.Observe.List("can.Model.List",{setup:function(){d.Observe.List.prototype.setup.apply(this,arguments);var a=this;this.bind("change",function(b,c){/\w+\.destroyed/.test(c)&&a.splice(a.indexOf(b.target),1)})}});d.Control.processors.route=function(a,b,c,e,f){d.route(c||"");var g,h=function(i){if(d.route.attr("route")===(c||"")&&(i.batchNum===n||i.batchNum!==g)){g=i.batchNum;i=d.route.attr();delete i.route;f[e](i)}};d.route.bind("change",h);return function(){d.route.unbind("change",
h)}};var Oa=function(a){eval(a)};p=d.extend;var Pa=/\r\n/g,Qa=/\r/g,Ra=/\n/g,Sa=/\\/g,Ta=/\t/g,Ua=/\{/g,Va=/\}/g,ta=/\s*\(([\$\w]+)\)\s*->([^\n]*)/,Wa=/([^\s]+)=$/,Xa=/__!!__/g,Ya={"":"span",table:"tr",tr:"td",ol:"li",ul:"li",tbody:"tr",thead:"tr",tfoot:"tr"},Za=function(a){return a.replace(Sa,"\\\\").replace(Ra,"\\n").replace(/"/g,'\\"').replace(Ta,"\\t")},ua=function(a){var b=a.match(Ua);a=a.match(Va);return(b?b.length:0)-(a?a.length:0)},K=function(a,b,c){d.each(a,function(e,f){f.obj.bind(f.attr,
c)});d.bind.call(b,"destroyed",function(){d.each(a,function(e,f){f.obj.unbind(f.attr,f.cb)})})},wa=function(a){return typeof a=="string"||typeof a=="number"?d.String.esc(""+a):va(a)},va=function(a){if(typeof a=="string")return a;if(a===null||a===n)return"";var b=a.hookup&&function(c,e){a.hookup.call(a,c,e)}||typeof a=="function"&&a;if(b)return"data-view-id='"+d.view.hook(b)+"'";return""+a},r=function(a){if(this.constructor!=r){var b=new r(a);return function(c,e){return b.render(c,e)}}if(typeof a==
"function")this.template={fn:a};else{p(this,a);this.template=$a(this.text,this.name)}};d.EJS=r;r.prototype.render=function(a,b){a=a||{};return this.template.fn.call(a,a,new r.Helpers(a,b||{}))};p(r,{txt:function(a,b,c,e,f){if(d.Observe)d.Observe.__reading=function(j,k){g.push({obj:j,attr:k})};var g=[],h=e.call(c);d.Observe&&delete d.Observe.__reading;if(!g.length)return(f||b!==0?wa:va)(h);a=Ya[a]||"span";if(b==0)return"<"+a+" data-view-id='"+d.view.hook(f?function(j){var k=j.parentNode,l=document.createTextNode(h);
k.insertBefore(l,j);k.removeChild(j);K(g,k,function(){l.nodeValue=e.call(c)})}:function(j){var k=function(m,s){m=d.view.frag(m);var v=d.$(d.map(m.childNodes,function(ab){return ab})),L=s[s.length-1];L.nextSibling?L.parentNode.insertBefore(m,L.nextSibling):L.parentNode.appendChild(m);d.remove(d.$(s));return v},l=k(h,[j]);K(g,j.parentNode,function(){l=k(e.call(c),l)})})+"'></"+a+">";else if(b===1){var i=e.call(c).replace(/['"]/g,"").split("=")[0];G.push(function(j){K(g,j,function(){var k=(e.call(c)||
"").replace(/['"]/g,"").split("=");newAttrName=k[0];newAttrName!=i&&i&&j.removeAttribute(i);newAttrName&&j.setAttribute(newAttrName,k[1])})});return h}else{G.push(function(j){var k=d.$(j),l;(l=d.data(k,"hooks"))||d.data(k,"hooks",l={});var m=j.getAttribute(b);k=m.split("__!!__");var s;if(l[b])l[b].funcs.push(e);else l[b]={render:function(){var v=0;return m.replace(Xa,function(){return wa(s.funcs[v++].call(c))})},funcs:[e],batchNum:n};s=l[b];k.splice(1,0,h);j.setAttribute(b,k.join(""));K(g,j,function(v){if(v.batchNum===
n||v.batchNum!==s.batchNum){s.batchNum=v.batchNum;j.setAttribute(b,s.render())}})});return"__!!__"}},esc:function(a,b,c,e){return r.txt(a,b,c,e,true)},pending:function(){if(G.length){var a=G.slice(0);G=[];return" data-view-id='"+d.view.hook(function(b){d.each(a,function(c,e){e(b)})})+"'"}else return""}});var bb=/(<%%|%%>|<%==|<%=|<%#|<%|%>|<|>|"|')/,H=null,x=null,X=null,xa=function(){return x?"'"+X.match(Wa)[1]+"'":H?1:0},G=[],$a=function(a,b){a=a.replace(Pa,"\n").replace(Qa,"\n").split(bb);var c=
"",e=["var ___v1ew = [];"],f=function(s,v){e.push("___v1ew.push(",'"',Za(s),'"'+(v||"")+");")},g=[],h,i=null,j=false,k="",l=0,m;for(H=x=X=null;(m=a[l++])!==n;){if(i===null)switch(m){case "<%":case "<%=":case "<%==":j=1;case "<%#":i=m;c.length>0&&f(c);c="";break;case "<%%":c+="<%";break;case "<":H=1;c+=m;j=0;break;case ">":H=0;if(j){f(c,',can.EJS.pending(),">"');c=""}else c+=m;break;case "'":case '"':if(H)if(x&&x===m)x=null;else if(x===null){x=m;X=h}default:if(h==="<")k=m.split(" ")[0];c+=m;break}else switch(m){case "%>":switch(i){case "<%":h=
ua(c);if(h==1){e.push("___v1ew.push(","can.EJS.txt('"+k+"',"+xa()+",this,function(){","var ___v1ew = [];",c);g.push({before:"",after:"return ___v1ew.join('')}));"})}else{i=g.length&&h==-1?g.pop():{after:";"};i.before&&e.push(i.before);e.push(c,";",i.after)}break;case "<%=":case "<%==":(h=ua(c))&&g.push({before:"return ___v1ew.join('')",after:"}));"});if(ta.test(c)){c=c.match(ta);c="function(__){var "+c[1]+"=can.$(__);"+c[2]+"}"}e.push("___v1ew.push(","can.EJS."+(i==="<%="?"esc":"txt")+"('"+k+"',"+
xa()+",this,function(){ return ",c,h?"var ___v1ew = [];":"}));");break}i=null;c="";break;case "<%%":c+="<%";break;default:c+=m;break}h=m}c.length>0&&f(c);e.push(";");a={out:"with(_VIEW) { with (_CONTEXT) {"+e.join("")+" return ___v1ew.join('')}}"};Oa.call(a,"this.fn = (function(_CONTEXT,_VIEW){"+a.out+"});\r\n//@ sourceURL="+b+".js");return a};r.Helpers=function(a,b){this._data=a;this._extras=b;p(this,b)};r.Helpers.prototype={view:function(a,b,c){return $View(a,b||this._data,c||this._extras)},list:function(a,
b){a.attr("length");for(var c=0,e=a.length;c<e;c++)b(a[c],c,a)}};d.view.register({suffix:"ejs",script:function(a,b){return"can.EJS(function(_CONTEXT,_VIEW) { "+(new r({text:b,name:a})).template.out+" })"},renderer:function(a,b){return r({text:b,name:a})}})})(can={},window);
